---
- name: Configure Puppet Server 5.x
  hosts: puppetserver.turbo.local

  vars:
    max_memory: 1g

  tasks:
    - name: Install RPM GPG Key
      copy:
        src: files/RPM-GPG-KEY-puppet5
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-puppet5
        owner: root
        group: root
        mode: 0644

    - name: Import RPM GPG Key
      command: rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-puppet5
      changed_when: "1 == 0"

    - name: Install Repo file
      copy:
        src: files/puppet5.repo
        dest: /etc/yum.repos.d/puppet5.repo
        owner: root
        group: root
        mode: 0644

    - name: Install dependency packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - java-1.8.0-openjdk
        - rubygem-deep_merge

    - name: Install Puppet packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - puppet-agent
        - puppetserver

    - name: Deliver puppetserver config
      template:
        src: templates/puppetserver.j2
        dest: /etc/sysconfig/puppetserver
        owner: root
        group: root
        mode: 0644

    - name: Deliver the puppet.conf config
      template:
        src: templates/puppet.conf.j2
        dest: /etc/puppetlabs/puppet/puppet.conf
        owner: root
        group: root
        mode: 0644


    - name: Start and enable service
      service:
        name: puppetserver
        state: started
        enabled: true
